#!/usr/bin/env python3
"""Generate checked-in VNI/VPS byte maps from VietUnicode's reference table."""

from __future__ import annotations

import argparse
from pathlib import Path

import requests
from bs4 import BeautifulSoup

SOURCE = "https://vietunicode.sourceforge.net/charset/"


def parse_hex(value: str) -> tuple[int, ...]:
    return tuple(int(part, 16) for part in value.strip().split())


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    response = requests.get(SOURCE, timeout=30)
    response.raise_for_status()
    soup = BeautifulSoup(response.text, "html.parser")
    tables = soup.find_all("table")
    if len(tables) < 2:
        raise RuntimeError("VietUnicode encoding table not found")
    rows = tables[1].find_all("tr", recursive=False)[1:]

    vni: list[tuple[tuple[int, ...], int]] = []
    vps: list[tuple[int, int]] = []
    for row in rows:
        cells = row.find_all("td", recursive=False)
        if len(cells) < 12:
            continue
        codepoint = int(cells[1].get_text(strip=True).removeprefix("U+"), 16)
        vni_bytes = parse_hex(cells[3].get_text(strip=True))
        vps_bytes = parse_hex(cells[5].get_text(strip=True))
        if len(vps_bytes) != 1:
            raise RuntimeError(f"VPS must be one byte: {vps_bytes}")
        vni.append((vni_bytes, codepoint))
        vps.append((vps_bytes[0], codepoint))

    if len(vni) != 134 or len(vps) != 134:
        raise RuntimeError(f"expected 134 rows, got VNI={len(vni)} VPS={len(vps)}")
    if len({encoded for encoded, _ in vni}) != len(vni):
        raise RuntimeError("duplicate VNI sequence")
    if len({encoded for encoded, _ in vps}) != len(vps):
        raise RuntimeError("duplicate VPS byte")

    lines = [
        "//! Generated by bench/generate_viet_legacy_maps.py.",
        f"//! Source: {SOURCE}",
        "//! Do not edit manually; regenerate and review the diff.",
        "",
        "pub(super) const VNI_MAP: &[(&[u8], char)] = &[",
    ]
    for encoded, codepoint in sorted(vni, key=lambda item: (-len(item[0]), item[0])):
        values = ", ".join(f"0x{byte:02X}" for byte in encoded)
        lines.append(f"    (&[{values}], '\\u{{{codepoint:X}}}'),")
    lines.extend(["];", "", "pub(super) const VPS_MAP: &[(u8, char)] = &["])
    for encoded, codepoint in sorted(vps):
        lines.append(f"    (0x{encoded:02X}, '\\u{{{codepoint:X}}}'),")
    lines.extend(["];", ""])
    args.output.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
